# Use the same image as the service
# This way we don't use any additional disk space
# and the volumes are already defined
ARG SERVICE_IMAGE
FROM ${SERVICE_IMAGE}

# common file is identical for backup and restore; so reuse the original
ADD common-backup /common-restore
ADD tar-restore /tar-restore
ADD mw-salcom-restore /mw-salcom-restore

CMD ["/mw-salcom-restore"]
