# Use the same image as the service
# This way we don't use any additional disk space
# and the volumes are already defined
ARG SERVICE_IMAGE
FROM ${SERVICE_IMAGE}

ADD common-backup /common-backup
ADD tar-backup /tar-backup
ADD mw-salcom-backup /mw-salcom-backup

CMD ["/mw-salcom-backup"]
